---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podtato-flux-repo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: podtato-flux-secret
  url: ssh://git@github.com/xCodeOwl/podtato-head
